services:
  - type: web_service
    name: judge0-api
    region: oregon
    env: docker
    dockerfilePath: ./Dockerfile
    branch: main
    plan: free
    envVars:
      - key: RAILS_ENV
        value: production
      - key: JUDGE0_DB_HOST
        fromDatabase:
          name: judge0-postgres
          property: host
      - key: JUDGE0_DB_USER
        fromDatabase:
          name: judge0-postgres
          property: user
      - key: JUDGE0_DB_PASSWORD
        fromDatabase:
          name: judge0-postgres
          property: password
      - key: JUDGE0_DB_NAME
        fromDatabase:
          name: judge0-postgres
          property: database
      - key: JUDGE0_REDIS_HOST
        fromDatabase:
          name: judge0-redis
          property: host
      - key: JUDGE0_REDIS_PASSWORD
        fromDatabase:
          name: judge0-redis
          property: password
    user: root
    healthCheckPath: "/ping"
    numInstances: 1
